language: java
jdk:
- openjdk7
script:
- ./gradlew check && ./gradlew seleniumXvfb && ./gradlew jacocoTestReport
- bin/deploy-reports.sh
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: h3jJJmdOEizOVdcVHA67utzjd5ph3VYq18hDqa/Lfid3jNgZcfDs8rW92eAvzTVGMyQN8bTxSdyVy39K/SojoY7fG9xvMlCPAo6LKbBFCgwLglIGnF76QY+zYwbjaFgnn9NKp2qDLWFz91LoQzaAlVeQJD5Ik6uuM7yspemCPFs=
  strategy: git
  app: geit-i-myllu
before_install:
- bin/deploy.sh
env:
  global:
  - secure: GUGrjwLgiIpXogO+D77wwwaJZi/QHcVm/5+uGuOJi0c2o6prGE/WTfhFqd0aRH5VKwPLOtw/zwp+8oMAeDusSi4a85wC1PKhS6WbDMeCV4DlbbLVNc8KyMtpfGEHvHttFWV1FS9TFWTxFbyuh6gDeXpaXCe87r/m0madiiU2tEw=
