language: java
jdk:
- openjdk7
script:
- ./gradlew check
- ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key:
    secure: h3jJJmdOEizOVdcVHA67utzjd5ph3VYq18hDqa/Lfid3jNgZcfDs8rW92eAvzTVGMyQN8bTxSdyVy39K/SojoY7fG9xvMlCPAo6LKbBFCgwLglIGnF76QY+zYwbjaFgnn9NKp2qDLWFz91LoQzaAlVeQJD5Ik6uuM7yspemCPFs=
  app: geit-i-myllu
before_install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:geit-i-myllu-staging.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- yes | heroku keys:add
- git push heroku master
env:
  global:
    secure: kTIYeU59yaS+GwdTKg9klgrfFf9bEwR2CnkLOAks7sGuwWUwopK7UoNK9KCTrxtcmk78UmkTUD5Bmdsvp8K+C3TuCPztwA58hhHioAJc47Z+1CkFo/hYMb8zWlRrpcxjzBfWh+bud/wUE1mvQDuNIVAvNrbQXxJpXSGow5/UgJo=
